### ISSUE TITLE
iOS crash on Pose tracking demo EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by laukaho** [homuler/MediaPipeUnityPlugin#417] opened 2022-01-17 07:03 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04): iOS 14.8
- Target Platform: iOS 14.8
- Mobile Device (if the target is Android or iOS):  iPhone XS
- MediaPipeUnityPlugin version or commit id: efc7664e3ed5d997ee618c364bd2256896a43aae
- Bazel version: 4.2.1
- GCC/G++ version:
- Android NDK version (if the target platform is Android):
- Xcode version (if the target platform is iOS): 13.1

**Describe the current behavior**
App crash after running for while. The crash timing is random. Sometime 10 mins but sometimes can run for an hour.

**Steps to reproduce the issue**
1. Choose pose tracking demo and run on the device for long period of time. 
2. Using front camera and choose 640x480 resolution
3. Target the camera on a looping video that have human dance.

**Full logs**
See https://docs.unity3d.com/Manual/LogFiles.html
<img width="1134" alt="Screenshot 2022-01-17 at 9 56 32 AM" src="https://user-images.githubusercontent.com/13497872/149702899-7115d620-3289-435c-973a-a100d09c73e3.png">
<img width="1169" alt="Screenshot 2022-01-17 at 9 56 43 AM" src="https://user-images.githubusercontent.com/13497872/149702910-73216c33-1910-438f-a962-2af208abcf38.png">

**Additional Context**
The above behaviour is running the demo in `Async` mode. Therefore, I have also tested on `Sync` mode. It seems the error will not occur. The demo can run for more than 2 hours in `Sync` mode

From the callback stack trace, I found out this is caused by the source code from mediapipe. I think `Sync` mode can prevent to trigger the last element in `mirrors_` so the bug cannot be triggered.

`mediapipe/framework/output_stream_manager.cc` line 191
```
 // mediapipe/framework/output_stream_manager.cc line 191 from https://github.com/google/mediapipe/
  for (int idx = 0; idx < mirror_count; ++idx) {
    const Mirror& mirror = mirrors_[idx];
    if (add_packets) {
      // If the stream is the last element in mirrors_, moves packets from
      // output_queue_. Otherwise, copies the packets.
      if (idx == mirror_count - 1) {
        mirror.input_stream_handler->MovePackets(mirror.id,
                                                 packets_to_propagate);
      } else {
        mirror.input_stream_handler->AddPackets(mirror.id,
                                                *packets_to_propagate);
      }
    }
    if (set_bound) {
      mirror.input_stream_handler->SetNextTimestampBound(mirror.id,
                                                         next_timestamp_bound);
    }
  }
```

Do you have any idea how to fix it? I would love to contribute in it. 
By the way, nice project. It helps me a lot.

**Comment by homuler** [comment] 2022-01-17 13:25
Thank you for reporting the issue.
I'd like to isolate the cause of the issue to know whether it is a bug in this plugin or in MediaPipe.
If it's a MediaPipe's bug, it'd be better to report it to MediaPipe dev team.

The code you attached still looks like something that would appear in the middle of a stack trace.
Do you know the exact line that will generate this error in [`OutputStreamObserver::Notify()`](https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/framework/graph_output_stream.cc#L69-L123) and [`StatusBuilder::StatusBuilder`](https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/framework/deps/status_builder.h#L56-L60)?
If you know the value of local variables or so in case of an error, they would be helpful too.

**Comment by laukaho** [comment] 2022-01-18 03:01
Sorry, I can't provide any local variables. Do I need to modify MediaPipe source code to log it?

But there is one thing that I am very curious. Since I found out that `sync` mode will not occur this issue. Can you explain a little bit about how does `Async` mode works? Is that thread handling is implemented in MediaPipe source code?

**Comment by homuler** [comment] 2022-01-20 07:39
> Sorry, I can't provide any local variables. Do I need to modify MediaPipe source code to log it?

How about this?
> Do you know the exact line that will generate this error in OutputStreamObserver::Notify() and StatusBuilder::StatusBuilder?

> Can you explain a little bit about how does Async mode works? Is that thread handling is implemented in MediaPipe source code?

I'm not sure what the question is about, but as you pointed out, the code that is causing the error is implemented by MediaPipe.
The difference between Sync mode and Async mode lies in how the outputs are received.
It's not complete yet, but see https://github.com/homuler/MediaPipeUnityPlugin/wiki/Advanced-Topics#getting-output-from-stream for more details.

**Comment by laukaho** [comment] 2022-01-24 02:41
> Do you know the exact line that will generate this error in OutputStreamObserver::Notify() and StatusBuilder::StatusBuilder?

Sorry. I cannot find out which line causing the error either.

Now, I finally work around by implementing C# threading to do the async mode instead. It solved my problem, although the root cause is not fixed

**Comment by patrick508** [comment] 2022-02-23 10:23
Same issue here. We notice these a lot more if we make a develop build. If we make a release build we barely see these.

**Comment by grayhong** [comment] 2022-04-01 10:51
> > Do you know the exact line that will generate this error in OutputStreamObserver::Notify() and StatusBuilder::StatusBuilder?
> 
> Sorry. I cannot find out which line causing the error either.
> 
> Now, I finally work around by implementing C# threading to do the async mode instead. It solved my problem, although the root cause is not fixed

@laukaho Hello! We are suffering from this issue too. How did you use C# threading to solve this problem? Do you mean you set mediapipe as sync mode and separately implemented the C# threading code to prevent blocking the main thread?

**Comment by laukaho** [comment] 2022-04-01 11:31
> > > Do you know the exact line that will generate this error in OutputStreamObserver::Notify() and StatusBuilder::StatusBuilder?
> > 
> > Sorry. I cannot find out which line causing the error either.
> > 
> > Now, I finally work around by implementing C# threading to do the async mode instead. It solved my problem, although the root cause is not fixed
> 
> @laukaho Hello! We are suffering from this issue too. How did you use C# threading to solve this problem? Do you mean you set mediapipe as sync mode and separately implemented the C# threading code to prevent blocking the main thread?

 Yes, extractly what I have done. You just move the sync mode code graphrunner.FetchNextValue() to a C# thread.

**Comment by grayhong** [comment] 2022-04-02 01:44
@laukaho Thank you so much! I will test this and check the throughput! 
@homuler 
I tested the non-blocking sync mode and found that the async mode can achieve 30fps on a low-end device, whereas the non-blocking sync mode can't. Any tips for performance optimization of the non-blocking sync mode?

**Comment by homuler** [comment] 2022-04-02 04:22
> the non-blocking sync mode can't achieve 30fps on a low-end device, whereas the async mode can.

It depends on the implementation and how you are measuring the FPS.

In the Non-blocking mode, `GraphRunner#TryGetNext` won't block the main thread (see [`OutputStream#TryGetNext`](https://github.com/homuler/MediaPipeUnityPlugin/blob/2497f0cae0ab60e12e1cabf5af69c27fb75fa27e/Assets/Mediapipe/Samples/Common/Scripts/OutputStream.cs#L98-L124) for more details).
However, if it doesn't return the result value, we can't tell whether it's because MediaPipe has not finished inferencing or because the result is just empty, so the sample app waits until at least the timeout period has elapsed.

https://github.com/homuler/MediaPipeUnityPlugin/blob/2497f0cae0ab60e12e1cabf5af69c27fb75fa27e/Assets/Mediapipe/Samples/Common/Scripts/ImageSourceSolution.cs#L106-L110
https://github.com/homuler/MediaPipeUnityPlugin/blob/2497f0cae0ab60e12e1cabf5af69c27fb75fa27e/Assets/Mediapipe/Samples/Scenes/Pose%20Tracking/PoseTrackingSolution.cs#L64-L67

So if the inference doesn't finish in 1 frame (e.g. 16ms if running at 60fps), it will wait for a few frames.
To mitigate this, you can lower the timeout period, but possibly just stopping calling `WaitUntil` may solve your problem (very similar behavior in the async mode).

**Comment by homuler** [comment] 2022-04-02 04:25
By the way, if anyone knows how to reproduce this more reliably, please let me know.

> Sometime 10 mins but sometimes can run for an hour.

With so many things to do, it is impossible to spend an hour just for reproduction.

**Comment by grayhong** [comment] 2022-04-02 15:45
> By the way, if anyone knows how to reproduce this more reliably, please let me know.
> 
> > Sometime 10 mins but sometimes can run for an hour.
> 
> With so many things to do, it is impossible to spend an hour just for reproduction.

Thank you so much @homuler! I will let you know if I find a way to reproduce this issue!

**Comment by homuler** [comment] 2022-04-08 09:51
I've not yet succeeded in reproducing this error, but one thing comes to mind.
In asynchronous mode, each callback function returns an `IntPtr`, which is a pointer to `absl::Status`.

https://github.com/homuler/MediaPipeUnityPlugin/blob/5222faa9a21e1c523614f8c082b92ec521c2005b/Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs#L380

From the managed code's point of view, this `Status` object is subject to GC.
If `Status#Dispose` is called while the underlying `absl::Status` is still referenced by the unmanaged code, I think it can cause SIGSEGV.

**Comment by homuler** [comment] 2022-04-09 03:39
In the `OutputStreamObserver::Notify()` code, there are 3 possible lines that initialize an instance of `mediapipe::StatusBuilder`.

1. https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/framework/graph_output_stream.cc#L91
   > ```cc
   >           MP_RETURN_IF_ERROR(packet_callback_(Packet().At(settled)));
   > ```

1. https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/framework/graph_output_stream.cc#L116-L118
   > ```cc
   >     RET_CHECK_EQ(num_packets_dropped, 0).SetNoLogging()
   >         << absl::Substitute("Dropped $0 packet(s) on input stream \"$1\".",
   >                             num_packets_dropped, input_stream_->Name());
   > ```

1. https://github.com/google/mediapipe/blob/6abec128edd6d037e1a988605a59957c22f1e967/mediapipe/framework/graph_output_stream.cc#L119
   > ```cc
   >     MP_RETURN_IF_ERROR(packet_callback_(packet));
   > ```

The 2nd initializes an `absl::Status` on the stack (not heap), so it's unlikely (or less likely) that this would cause `EXC_BAD_ACCESS`.
I think there is most likely a problem with the `Status` returned by `packet_callback_`.

To determine the cause, we still need to know
1. which of the above 3 lines is causing the problem
2. what is the `Status` that is returned by `packet_callback_` (i.e. `Status.Ok` / `Status.FailedPrecondition`, etc...)
3. and if the returned `Status` is disposed of or not.

**Comment by homuler** [comment] 2022-04-09 05:13
@laukaho @grayhong @patrick508 
Can you confirm this error still occurs with the latest commit (https://github.com/homuler/MediaPipeUnityPlugin/commit/5222faa9a21e1c523614f8c082b92ec521c2005b)?
While I tried running the sample app on my iPad Air (4th) for about 90 mins, I could not reproduce it.

**Comment by siisee11** [comment] 2022-04-11 05:32
@homuler 
Hi, I agree that Garbage Collection causes the `EXC_BAD_ACCESS` error. So in my opinion, this error will not be reproduced while running the sample app, it needs memory pressure to reproduce. Could I ask how you try to prevent garbage collection of `IntPtr`?

**Comment by homuler** [comment] 2022-04-11 12:32
> Can you confirm this error still occurs with the latest commit (https://github.com/homuler/MediaPipeUnityPlugin/commit/5222faa9a21e1c523614f8c082b92ec521c2005b)?

@siisee11 I would like to know if this problem occurs in the first place.
I just thought it might be GC related if it occurs, but I don't understand what execution path it occurs on (I could not reproduce the error even if I modified `absl::Status` code and released the memory).

> Could you explain how you try to prevent garbage collection of IntPtr? https://github.com/homuler/MediaPipeUnityPlugin/pull/516

You can store the `Status` to a member variable.

**Comment by homuler** [comment] 2022-04-12 08:30
@grayhong 
I see. Can you share your crash report (of course, please hide confidential information) with me?
I'd like to know the exact line (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/417#issuecomment-1093645717) that triggers this error.

If this is not possible, I'm glad if you tell me the offset from `OutputStreamObserver::Notify()`, which should jump to the `StatusBuilder` constructor code.

> I'll test the fix you added
>> You can store the Status to a member variable.

Just to be clear, the fix is not in the master branch.

**Comment by grayhong** [comment] 2022-04-12 10:14
> @grayhong I see. Can you share your crash report (of course, please hide confidential information) with me? I'd like to know the exact line (cf. [#417 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/417#issuecomment-1093645717)) that triggers this error.
> 
> If this is not possible, I'm glad if you tell me the offset from `OutputStreamObserver::Notify()`, which should jump to the `StatusBuilder` constructor code.
> 
> > I'll test the fix you added
> > > You can store the Status to a member variable.
> 
> Just to be clear, the fix is not in the master branch.

Sure! Is there any channel that I can send a message to you? (ex. Discord)

**Comment by grayhong** [comment] 2022-04-12 10:25
> @grayhong I see. Can you share your crash report (of course, please hide confidential information) with me? I'd like to know the exact line (cf. [#417 (comment)](https://github.com/homuler/MediaPipeUnityPlugin/issues/417#issuecomment-1093645717)) that triggers this error.
> 
> If this is not possible, I'm glad if you tell me the offset from `OutputStreamObserver::Notify()`, which should jump to the `StatusBuilder` constructor code.
> 
> > I'll test the fix you added
> > > You can store the Status to a member variable.
> 
> Just to be clear, the fix is not in the master branch.

Here it is!
```
Crashed: mediapipe/0
0  MediaPipeUnity                 0xd1a0 mediapipe::StatusBuilder::StatusBuilder(absl::lts_20210324::Status const&, char const*, int) + 136
1  MediaPipeUnity                 0x87031c mediapipe::internal::OutputStreamObserver::Notify() + 304
2  MediaPipeUnity                 0x869838 _hidden#11721_ + 16848
3  MediaPipeUnity                 0x88ce80 mediapipe::InputStreamHandler::SetNextTimestampBound(mediapipe::CollectionItemId, mediapipe::Timestamp) + 160
4  MediaPipeUnity                 0x88b238 mediapipe::OutputStreamManager::PropagateUpdatesToMirrors(mediapipe::Timestamp, mediapipe::OutputStreamShard*) + 624
5  MediaPipeUnity                 0x889ff4 mediapipe::OutputStreamHandler::PropagateOutputPackets(mediapipe::Timestamp, mediapipe::internal::Collection<mediapipe::OutputStreamShard, (mediapipe::internal::CollectionStorage)0, mediapipe::internal::CollectionErrorHandlerFatal<mediapipe::OutputStreamShard> >*) + 160
6  MediaPipeUnity                 0x8840e4 mediapipe::CalculatorNode::ProcessNode(mediapipe::CalculatorContext*) + 1160
7  MediaPipeUnity                 0x875a7c mediapipe::internal::SchedulerQueue::RunCalculatorNode(mediapipe::CalculatorNode*, mediapipe::CalculatorContext*) + 300
8  MediaPipeUnity                 0x875524 mediapipe::internal::SchedulerQueue::RunNextTask() + 232
9  MediaPipeUnity                 0x8a73e0 mediapipe::ThreadPool::RunWorker() + 364
10 MediaPipeUnity                 0x8a6f34 mediapipe::ThreadPool::WorkerThread::ThreadBody(void*) + 404
11 libsystem_pthread.dylib        0x19ac _pthread_start + 148
12 libsystem_pthread.dylib        0xe68 thread_start + 8
```

**Comment by grayhong** [comment] 2022-04-12 10:30
> Just to be clear, the fix is not in the master branch.
@homuler By the way, isn't the commit `5222faa` in master branch?

**Comment by homuler** [comment] 2022-04-12 11:09
Thanks!

> By the way, isn't the commit 5222faa in master branch?

It's in a master, but it is not a fix (rather refactoring).

**Comment by siisee11** [comment] 2022-04-13 04:52
@homuler, still has an issue (EXC_BAD_ACCESS) on https://github.com/homuler/MediaPipeUnityPlugin/commit/5222faa9a21e1c523614f8c082b92ec521c2005b commit

**Comment by homuler** [comment] 2022-04-13 04:59
@siisee11 Can you share the stack trace (or screenshots)?
Based on the information so far, it appears that the error can occur at different lines.

**Comment by homuler** [comment] 2022-04-16 08:30
Can anyone test to see if https://github.com/homuler/MediaPipeUnityPlugin/commit/78b2d1a3e2c6be98249689cd54ee5d228a123498 fixes the problem?

**Comment by grayhong** [comment] 2022-04-18 11:30
> Can anyone test to see if [78b2d1a](https://github.com/homuler/MediaPipeUnityPlugin/commit/78b2d1a3e2c6be98249689cd54ee5d228a123498) fixes the problem?

I'll try it! Thank you so much!

**Comment by grayhong** [comment] 2022-04-18 11:32
@homuler Btw, I found different crash with same exception (EXC_BAD_ACCESS). It appears quite often in low-end device (iPhone 7+) 

<img width="1355" alt="mp_error" src="https://user-images.githubusercontent.com/20103062/163802354-3158960e-652d-4756-9baa-7a79e5e08f1d.png">
<img width="1078" alt="mp_stack" src="https://user-images.githubusercontent.com/20103062/163802314-8075e070-3940-40af-bdec-8f1790cdf470.png">

**Comment by homuler** [comment] 2022-04-18 12:27
@grayhong Thank you for reporting the issue.

Perhaps the cause and the conditions are different, so create another issue if necessary.
A recent commit (not released yet) just relates to `CreateCVPixelBufferForImageFramePacket` (https://github.com/google/mediapipe/commit/cc6a2f7af65977248b2a15f471503da2832f583a#diff-bef471e93b87c12ce09a9413971a44005287f038b57d58d5e6213ef377d2d61a), but I don't know if it's related to this error.

**Comment by siisee11** [comment] 2022-04-27 15:01
@homuler I tested https://github.com/homuler/MediaPipeUnityPlugin/commit/78b2d1a3e2c6be98249689cd54ee5d228a123498. I'm not 100% sure (need to try more), but It seems to fix the original issue. As @grayhong mentioned, there is a crash issue related to CreateCVPixelBufferForImageFramePacket. I'll create a new issue with details.

Thank you for resolving the issues!

**Comment by homuler** [comment] 2022-04-28 01:22
@siisee11 Thanks!
I'll wait another week or two, and if there are no reports, I'll merge it into master.

**Comment by laukaho** [comment] 2022-05-03 10:10
I also tested [`78b2d1a`](https://github.com/homuler/MediaPipeUnityPlugin/commit/78b2d1a3e2c6be98249689cd54ee5d228a123498) and run on IPad Mini 6 for 2 hours.
The crash didn't happened. Let's see if there are more testing result in the future. 
Thanks for the fix @homuler

**Closed** 2022-05-12 07:02 UTC
Labels: type:bug, sect:plugin, stat:condition unknown
