### ISSUE TITLE
Build Andorid Library Failed-Connect timed out

### ISSUE THREAD

**Issue by HakuWang** [homuler/MediaPipeUnityPlugin#536] opened 2022-04-18 03:58 UTC
### Plugin Version or Commit ID

v0.8.3

### Unity Version

2020.3.30f1

### Your Host OS

Windows 10

### Target Platform

Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

VisualStudio C++: 14.29.30133
Windows SDK: 10.0.19041.0

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.2
NDK：19.0.5232133

### Command Sequences

docker build -t mediapipe_unity:linux . -f docker/linux/x86_64/Dockerfile

docker run --cpus=6 --memory=16g --mount type=bind,src=E:\SVN\YZDH\VideoBasedFacialAnim\MediaPipeUnityPluginDocker\Packages,dst=/home/mediapipe/Packages --mount type=bind,src=E:\SVN\YZDH\VideoBasedFacialAnim\MediaPipeUnityPluginDocker\Assets,dst=/home/mediapipe/Assets -it mediapipe_unity:linux

python build.py build --android arm64 -vv

### Log

INFO (build.py): Building protobuf sources...
DEBUG (build.py): Running `bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs`
2022/04/18 02:08:02 Downloading https://releases.bazel.build/4.2.1/release/bazel-4.2.1-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz failed: class java.io.IOException connect timed out
INFO: Repository build_bazel_rules_apple instantiated at:
  /home/mediapipe/WORKSPACE:341:13: in <toplevel>
Repository rule http_archive defined at:
  /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_apple/releases/download/0.32.0/rules_apple.0.32.0.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
        File "/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.32.0/rules_apple.0.32.0.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/build_bazel_rules_apple/temp7019480873336431819/rules_apple.0.32.0.tar.gz: connect timed out
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.32.0/rules_apple.0.32.0.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/build_bazel_rules_apple/temp7019480873336431819/rules_apple.0.32.0.tar.gz: connect timed out
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.32.0/rules_apple.0.32.0.tar.gz] to /home/mediapipe/.cache/bazel/_bazel_mediapipe/6c11c387a04fa8f17c87a5c6db6ee555/external/build_bazel_rules_apple/temp7019480873336431819/rules_apple.0.32.0.tar.gz: connect timed out
INFO: Elapsed time: 406.781s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Traceback (most recent call last):
  File "/home/mediapipe/build.py", line 448, in <module>
    Argument().command().run()
  File "/home/mediapipe/build.py", line 114, in run
    self._run_command(self._build_proto_srcs_commands())
  File "/home/mediapipe/build.py", line 54, in _run_command
    return subprocess.run(' '.join(command_list), check=True, shell=shell)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel build -c opt --verbose_failures //mediapipe_api:mediapipe_proto_srcs' returned non-zero exit status 1.

### Additional Context

i built successfully by [Docker Windows Container] last month, but i skipped the step 5 during the building.

now i want to build an android apk. My understanding is that i need to build android library first, then i can build the apk by unity editor like normal unity games. Is my understanding correct?

i followed the instructions in https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker-linux-container to build android library and got errors in the log. It seems like something about network, but i am not sure.  i'd appreciate it if you could help me.

**Comment by homuler** [comment] 2022-04-18 08:36
> now i want to build an android apk. My understanding is that i need to build android library first, then i can build the apk by unity editor like normal unity games. Is my understanding correct?

Yes.

>  It seems like something about network, but i am not sure.

I think it's a network issue, too.

I've just merged #537, which allows arbitrary options to be passed to Bazel.
With this change, we can change the timeout configuration (cf. https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_scale_timeouts).

```sh
python build.py build --bazel_build_opts "--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0" --android arm64 -vv
```

I hope these options will mitigate your issue (note that you need to rebuild the Docker image to copy this new `build.py`).

**Comment by HakuWang** [comment] 2022-04-19 01:58
Thank you for your help.

I tried to reinstall my docker desktop and rebuild the Docker image with the same build command. But i got errors below:

**Comment by homuler** [comment] 2022-04-19 03:36
You should specify `MIRROR_COUNTRY` (cf. https://github.com/homuler/MediaPipeUnityPlugin/wiki/Installation-Guide#docker).
See also https://wiki.archlinux.org/title/mirrors#Fetching_and_ranking_a_live_mirror_list.

P.S.
> I tried to reinstall my docker desktop

I don't know why you had to reinstall Docker Desktop, but it should have cleared your local cached layers.
Usually, it doesn't take a long time to rebuild a Docker image.

**Comment by HakuWang** [comment] 2022-04-22 02:45
Thanks a lot.

 I tried many times and strived to improve internet speed. I  also replaced the build.py with the #537 version, and used the build command you provided. I don't know exactly which modification made the difference. Anyway now i built android library successfully and built an apk with unity editor.

By the way, i met the DllNotFoundException problem on my elder device. On another android device, the apk can run except that the displayed image is y-flipped. I used the command "adb shell getprop ro.build.version.sdk" to check api level for my android device and got "26". I'm tring to rebuild with option --android_ndk_api_level 21.  Is this the right way to solve this problem ?

**Comment by homuler** [comment] 2022-04-22 03:24
> I checked the TroubleShooting part on wiki and now I'm tring to rebuild the android library with option "--android_ndk_api_level 21". Is this the right way to solve this problem ?

Maybe, but it depends on the cause.
If some symbols are missing, specifying `--android_ndk_api_level` will resolve the issue.
For example, I guess your device does not support `aligned_alloc`, which is introduced at API level 28 (cf. https://android.googlesource.com/platform/bionic/+/master/docs/status.md).

On the other hand, if the CPU of your device is armv7, you may want to build libraries with the `--android fat` option.
See also https://github.com/homuler/MediaPipeUnityPlugin/issues/171#issuecomment-850154795.

> On another android device, the apk can run except that the displayed image is y-flipped.

I hope this issue is already fixed by https://github.com/homuler/MediaPipeUnityPlugin/pull/504 (included in v0.8.4).

**Comment by HakuWang** [comment] 2022-04-22 07:32
> On the other hand, if the CPU of your device is armv7, you may want to build libraries with the `--android fat` option.

i also checked cpu, my device is arm64.

> For example, I guess your device does not support `aligned_alloc`, which is introduced at API level 28 (cf. https://android.googlesource.com/platform/bionic/+/master/docs/status.md).

Yes, this is my situation. But after rebuild the android library specifying --android_ndk_api_level, my older device still got the same problem. here is my logs from monitor:

04-22 15:24:18.145: E/Unity(16419): AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.uz.mediapipe-EjANcZ7MKrpPeB9M8FuoSQ==/lib/arm64/libmediapipe_jni.so"...
04-22 15:24:18.145: E/Unity(16419): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.uz.mediapipe-EjANcZ7MKrpPeB9M8FuoSQ==/lib/arm64/libmediapipe_jni.so"...
04-22 15:24:18.145: E/Unity(16419):      at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
04-22 15:24:18.145: E/Unity(16419):      at java.lang.System.loadLibrary(System.java:1660)
04-22 15:24:18.145: E/Unity(16419):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
04-22 15:24:18.145: E/Unity(16419):      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
04-22 15:24:18.145: E/Unity(16419):      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
04-22 15:24:18.145: E/Unity(16419):      at android.os.Handler.dispatchMessage(Handler.java:104)
04-22 15:24:18.145: E/Unity(16419):      at android.os.Looper.loop(Looper.java:166)
04-22 15:24:18.145: E/Unity(16419):      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
04-22 15:24:18.145: E/Unity(16419):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
04-22 15:24:18.145: E/Unity(16419):   at UnityEngine.AndroidJNISafe.CallStaticVoidMethod (System.IntP
04-22 15:24:18.347: E/Unity(16419): DllNotFoundException: Unable to load DLL 'mediapipe_jni': The specified module could not be found.
04-22 15:24:18.347: E/Unity(16419):   at Mediapipe.Glog.set_Logtostderr (System.Boolean value) [0x00000] in <00000000000000000000000000000000>:0
04-22 15:24:18.347: E/Unity(16419):   at Mediapipe.Unity.GlobalConfigManager.SetFlags () [0x00000] in <00000000000000000000000000000000>:0
04-22 15:24:18.347: E/Unity(16419):   at Mediapipe.Unity.Bootstrap+<Start>d__17.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
04-22 15:24:18.347: E/Unity(16419):   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0

**Comment by HakuWang** [comment] 2022-04-22 08:24
> On the other hand, if the CPU of your device is armv7, you may want to build libraries with the --android fat option.
i also checked cpu, my device is arm64.

> For example, I guess your device does not support aligned_alloc, which is introduced at API level 28 (cf. https://android.googlesource.com/platform/bionic/+/master/docs/status.md).
Yes, this is my situation. But after rebuilt the android library specifying --android_ndk_api_level, my older device still got the same problem. 

here is my logs from monitor:
04-22 16:18:15.177: E/Unity(19456): AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.uz.mediapipe-tK8jkDZtVsdrHfrQVx2y8w==/lib/arm64/libmediapipe_jni.so"...
04-22 16:18:15.177: E/Unity(19456): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.uz.mediapipe-tK8jkDZtVsdrHfrQVx2y8w==/lib/arm64/libmediapipe_jni.so"...
04-22 16:18:15.177: E/Unity(19456):      at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
04-22 16:18:15.177: E/Unity(19456):      at java.lang.System.loadLibrary(System.java:1660)
04-22 16:18:15.177: E/Unity(19456):      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
04-22 16:18:15.177: E/Unity(19456):      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
04-22 16:18:15.177: E/Unity(19456):      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
04-22 16:18:15.177: E/Unity(19456):      at android.os.Handler.dispatchMessage(Handler.java:104)
04-22 16:18:15.177: E/Unity(19456):      at android.os.Looper.loop(Looper.java:166)
04-22 16:18:15.177: E/Unity(19456):      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
04-22 16:18:15.177: E/Unity(19456):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
04-22 16:18:15.177: E/Unity(19456):   at UnityEngine.AndroidJNISafe.CallStaticVoidMethod (System.IntP

04-22 16:18:15.315: D/Unity(19456): Failed to load native plugin: Unable to load library '/data/app/com.uz.mediapipe-tK8jkDZtVsdrHfrQVx2y8w==/lib/arm64/libmediapipe_jni.so', error 'java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.uz.mediapipe-tK8jkDZtVsdrHfrQVx2y8w==/lib/arm64/libmediapipe_jni.so"...'
04-22 16:18:15.400: E/Unity(19456): DllNotFoundException: Unable to load DLL 'mediapipe_jni': The specified module could not be found.
04-22 16:18:15.400: E/Unity(19456):   at Mediapipe.Glog.set_Logtostderr (System.Boolean value) [0x00000] in <00000000000000000000000000000000>:0
04-22 16:18:15.400: E/Unity(19456):   at Mediapipe.Unity.GlobalConfigManager.SetFlags () [0x00000] in <00000000000000000000000000000000>:0
04-22 16:18:15.400: E/Unity(19456):   at Mediapipe.Unity.Bootstrap+<Start>d__17.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
04-22 16:18:15.400: E/Unity(19456):   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0

**Comment by homuler** [comment] 2022-04-22 09:37
I see.
As mentioned in [the Build / Install issue form](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/.github/ISSUE_TEMPLATE/build-install-issue.yml), when you have trouble with building libraries, please download _the latest version_ (v0.9.1 at the moment).
The Installation Guide is written for the latest version, so the methods described in it do not necessarily work for older versions.

> I also replaced the build.py with the https://github.com/homuler/MediaPipeUnityPlugin/pull/537 version,

Maybe you just downloaded `build.py` and didn't pull the commit, did you?
v0.8.3 does not contain [changes](https://github.com/homuler/MediaPipeUnityPlugin/pull/496) to make `--android_ndk_api_level` option work.

**Comment by HakuWang** [comment] 2022-04-22 10:25
> Maybe you just downloaded `build.py` and didn't pull the commit, did you?
I didn't pull the whole commit. Since i have made many modifications, i need to check if i could update to the latest version easily. 

If i could make --android_ndk_api_level option work, which level should i specified ?  26(same as my device) or 19 (same as unity used during building) ?

Thank you for your help.

**Comment by homuler** [comment] 2022-04-22 10:51
I think `21` will do.
At v0.8.3, you need to modify `WORKSPACE` file to specify `api_level` (cf. https://github.com/homuler/MediaPipeUnityPlugin/pull/270).

You can check if you have built `mediapipe_android.aar` correctly as follows:
```sh
unzip mediapipe_android.aar
objdump -T jni/arm64-v8a/libmediapipe_jni.so | grep aligned_malloc
```

**Comment by HakuWang** [comment] 2022-04-22 13:42
> I think `21` will do.
> At v0.8.3, you need to modify `WORKSPACE` file to specify `api_level` (cf. #270).

Yes, I modified `WORKSPACE` file, rebuilt the image and rebuilt mediapipe_android.aar as you said. Now it works on my device.
Thank you so much !

**Closed** 2022-04-23 01:39 UTC
Labels: type:build/install

**Comment by 9276** [comment] 2022-05-07 03:07
i want to how use MediaPipeUnityPlugin。can you tell me step
