### ISSUE TITLE
Android build shows the background Render Texture rotated 90 degrees

### ISSUE THREAD

**Issue by LoopIssuer** [homuler/MediaPipeUnityPlugin#665] opened 2022-07-22 19:54 UTC
### Plugin Version or Commit ID

v0.10.0

### Unity Version

2021.3.4f1

### Your Host OS

Windows 10 Home

### Target Platform

Android

### [Windows Only] Visual Studio C++ and Windows SDK Version

Microsoft Visual Studio Community 2019
Version 16.11.15
Windows SDK 10.0.16299.0

### [Android Only] Android Build Tools and NDK Version

Build Tools: 30.0.2
NDK : 21.3

### Command Sequences

Hi,

When I use the Selfie Segmentation sample, and change the background to show Render Texture (and view from another camera with Render Texture) instead of green screen, there is everything ok in the editor.

However, the Android build shows the background rotated 90 degrees. (Person shown with the camera is ok, but the background texture is rotated).

Could you please help me find a solution or give any hint?

### Log

no log

**Comment by homuler** [comment] 2023-01-21 06:50
close it since it can't be reproduced with the sample app and the condition is not clear.

**Closed by homuler** 2023-01-21 06:50 UTC
Labels: type:bug
