### ISSUE TITLE
The memory usage is very high when using video as input.

### ISSUE THREAD

**Issue by Longgood-Anny** [homuler/MediaPipeUnityPlugin#352] opened 2021-11-18 09:54 UTC
As the title, when I use the camera as input, it will be fine.
But when I use the video as input, the memory usage will be very high and cause the crash of the App.
(Both synchronous and asynchronous will cause this problem)
It even uses all the memory on my MacBook Pro, and the result will be the same if I build on iPhone7.

The error log will be like `UnityGfxDeviceWorker (28): EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=1450 MB, unused=0x0)` in XCode.
![截圖 2021-11-18 下午5 25 04](https://user-images.githubusercontent.com/93504662/142387841-c68494ec-3d32-4e74-b5d2-f52b44588dc5.png)

And I also try to Enable/Disable the GameObject `Solution` at runtime.
The memory usage will stop increasing when I disable the `Solution`.(But the value of the memory usage won't decrease)

I want to know if anyone has the same situation as me.
I don't have a clue why this happened.

thank you!

p.s. the video I used is only 4.5MB.

**Comment by Onkar-G** [comment] 2021-11-25 00:32
How did you give video as an input ?

**Comment by Longgood-Anny** [comment] 2021-11-29 03:44
> How did you give video as an input ?

1. Change the StartScene > Bootstrap > Default Image Source to Video.
2. Set the video to Image Source > Video Source >  Available Source.

**Comment by homuler** [comment] 2021-11-29 10:23
What is the resolution of the video?
Also, what is the resolution of the camera you are comparing?

**Comment by phantasylab-bbhgu** [comment] 2021-12-01 05:50
I have same problem too. The resolution of the video I used is as follows.
1.  1280 * 720
2.  1280 * 720

And my resolution of the camera(Used laptop webcam) is (1920 * 1080)

The cause of the problem was found in Run() of the PoseTracking Solution class. This is the 138th line of code in Run() _graphRunner.AddTextureFrameToInputStream.If you erase the AssertOk(); part, there will be no problem. Perhaps the same problem occurs in this area for other solution class.

**Comment by homuler** [comment] 2021-12-01 06:53
I've confirmed the issue.
I've also identified the cause and will fix it later.

**Comment by phantasylab-bbhgu** [comment] 2021-12-01 10:14
I found a solution! This is because the **tmpRenderTexture** buffer is not emptied from the **ReadTextureFromOnCPU (Texture src)** of the **TextureFrame** class.

![image](https://user-images.githubusercontent.com/29273551/144215603-a1e59564-593f-471e-9f53-9b9a662e0aa4.png)

If there's any other problem, please let me know.

**Comment by Longgood-Anny** [comment] 2021-12-02 01:51
> I found a solution! This is because the **tmpRenderTexture** buffer is not emptied from the **ReadTextureFromOnCPU (Texture src)** of the **TextureFrame** class.
> 
> ![image](https://user-images.githubusercontent.com/29273551/144215603-a1e59564-593f-471e-9f53-9b9a662e0aa4.png)
> 
> If there's any other problem, please let me know.

I followed this step and solved the problem!
If others have the same problem, you can also try this step~

Thank you both for your assistance!😄

**Comment by homuler** [comment] 2021-12-02 02:52
Fixed by https://github.com/homuler/MediaPipeUnityPlugin/commit/cab8e26cb627f393f6dcbc3849b1675f39f56427

**Closed by homuler** 2021-12-02 02:52 UTC
Labels: bug, performance
