### ISSUE TITLE
The sample app crashes on Samsung 22 Ultra

### ISSUE THREAD

**Issue by gb2111** [homuler/MediaPipeUnityPlugin#821] opened 2022-12-27 10:45 UTC
### Plugin Version or Commit ID

0.10.1

### Unity Version

2021.3.3f1

### Your Host OS

Windows

### Target Platform

Windows Standalone

### Description

I am trying to build sample scenes on Windows.  I am using pre-compiled version.
Imported to my project via Packet Manager - Import Folder.
It didn't import Samples so I have copied them manually from the GitHub (In the pre-compiled package there was no Start Scene).
I started Start Scene in Unity but there was exception `(...)/AppData/LocalLow/DefaultCompany/TestMediapipe\pose_detection.bytes is not found`. When I copied all .bytes files to that folder it started working. My question is how can I ensure that it works without copying to this folder and is part of compilation?
Also I want to ask how can I ensure that on Android and iOS cause I have compiled also Android version some time ago and it just show me camera. I am assuming the problem was similar.

Thanks for your help.

**Comment by gb2111** [comment] 2022-12-27 13:47
I captured logcat from player on Android (adb logcat | grep -e "Unity" ). Can't see any errors there.
[Player-logcat.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10308452/Player-logcat.txt)

**Comment by homuler** [comment] 2022-12-27 14:15
> It didn't import Samples so I have copied them manually from the GitHub

You can also import samples using Package Manager (see https://docs.unity3d.com/Manual/upm-ui.html).
The `Start Scene` is not included in the package because it doesn't work by default  in the project to which it is imported.
See also https://github.com/homuler/MediaPipeUnityPlugin/issues/727#issuecomment-1231018607.

> I captured logcat from player on Android (adb logcat | grep -e "Unity" ). Can't see any errors there.

Try `adb logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"`

**Comment by gb2111** [comment] 2022-12-27 14:33
Thanks for reply. Here is the log using the command you have provided. 
[Player-logcat.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10308697/Player-logcat.txt)

I impoered precompiled package using Packet Manager and "Add package from disk" and pointing to package.json and there were no samples included.

So you are saying I need to modify samples to load model files?

Thanks.

**Comment by homuler** [comment] 2022-12-27 14:53
Please read the linked document first (especially https://github.com/homuler/MediaPipeUnityPlugin/issues/727#issuecomment-1231018607).

> Here is the log using the command you have provided.

Will you show me that the sample app isn't actually working on your device?
Does it work in sync mode? (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/661)

> there were no samples included.

Click the `import` button.
![package-manager](https://user-images.githubusercontent.com/4690128/209682674-341a0fc3-01ff-4073-bb82-f1290085c2ca.png)

**Comment by gb2111** [comment] 2022-12-27 16:01
Hello. I have created empty project. Imported plugin, imported Official Solutions, copied SteamingAssets and changed Assset Loader Type to Streaming Asssets. That should be all steps I noted. However I have some error when starting apk related to camera. I don't see this when running in Editor.
[Player-log.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10309469/Player-log.txt)

Thanks

**Comment by homuler** [comment] 2022-12-27 16:14
What is your Android device?
Have you permitted the app to use the camera?

**Comment by gb2111** [comment] 2022-12-27 16:37
It is samsung 22 ultra.
It asks first time to use camera and I allow that.

When I open Image Source Settingts I see Type is WebCamera and Source is Camera 0. Resolution is 0x0. 
When I change Source to Camera 1 I have 1280x720 or something like that and one more resolution. But when I press exit nothing happens. I am getting this in the logcat

--------- beginning of main
12-27 17:36:49.132 29685 29721 E Unity   : InvalidOperationException: WebCamTexture is not prepared yet
12-27 17:36:49.132 29685 29721 E Unity   :   at Mediapipe.Unity.WebCamSource+<Resume>d__42.MoveNext () [0x00089] in /Users/greg/Documents/TestMediaPipe/Assets/Samples/MediaPipe Unity Plugin/0.10.1/Official Solutions/Common/Scripts/ImageSource/WebCamSource.cs:218
12-27 17:36:49.132 29685 29721 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00020] in /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17
12-27 17:36:49.132 29685 29721 E Unity   : UnityEngine.MonoBehaviour:StartCoroutineManaged2(MonoBehaviour, IEnumerator)
12-27 17:36:49.132 29685 29721 E Unity   : UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/MonoBehaviour.bindings.cs:91)
12-27 17:36:49.132 29685 29721 E Unity   : Mediapipe.Unity.ImageSourceSolution`1:Resume() (at /Users/greg/Documents/TestMediaPipe/Assets/Samples/MediaPipe Unity Plugin/0.10.1/Official Solutions/Common/Scripts/ImageSourceSolution.cs:47)
12-27 17:36:49.132 29685 29721 E Unity   : Mediapipe.Unity.UI.Modal:CloseAndResume(Boolean) (at /Users/greg/Documents/TestMediaPipe/Assets/Samples

**Comment by homuler** [comment] 2022-12-27 17:07
What is the value of `valueOfWebCamDevice.availableResolutions`?
If it's null, is it always so? Or if we wait for some time, it can be not null?

**Comment by gb2111** [comment] 2022-12-27 17:40
I should add this to log myself or there is other way to check ?

**Comment by gb2111** [comment] 2022-12-27 19:08
I added logs to the place you mentioned. Name is 'Camera 0'.
But I can't get to log resolution cause it is always crashing. Even if I am checking if it is null there is crash. If I catch exception when checking this camera I have also crash.

**Comment by homuler** [comment] 2022-12-28 07:40
I hope the original issue is resolved by [the latest release](https://github.com/homuler/MediaPipeUnityPlugin/releases/tag/v0.10.3) (`MediaPipeUnityPlugin-all.zip` contains all the required files to build the sample app including `StreamingAssets/`).

Will you apply the following patch and share the log?
```diff
diff --git a/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs b/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs
index 59c3d2d..f0ace2a 100644
--- a/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs
+++ b/Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs
@@ -110,6 +110,11 @@ namespace Mediapipe.Unity
       {
 #if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
         if (webCamDevice is WebCamDevice valueOfWebCamDevice) {
+          if (valueOfWebCamDevice.availableResolutions == null)
+          {
+            Debug.Log("availableResolutions is null");
+            return _defaultAvailableResolutions;
+          }
           return valueOfWebCamDevice.availableResolutions.Select(resolution => new ResolutionStruct(resolution)).ToArray();
         }
 #endif
```

> Even if I am checking if it is null there is crash.

If it really crashes when just accessing `WebCamDevice#availableResolutions`, I think you should report it to Unity as a bug.

**Comment by gb2111** [comment] 2022-12-28 09:59
Hello.
I added this code for bit more logs:
```
                    if (valueOfWebCamDevice.availableResolutions == null)
                    {
                        Debug.Log("availableResolutions is null");
                        return _defaultAvailableResolutions;
                    }
                    else
                    {
                        Debug.Log("availableResolutions is not null");
                        Debug.Log("availableResolutions: " + valueOfWebCamDevice.availableResolutions);

                        return valueOfWebCamDevice.availableResolutions.Select(resolution => new ResolutionStruct(resolution)).ToArray();
                    }
```

And got this. So it is not null but when trying to access it app crashes.

<sub>
12-28 10:54:00.402  4697  4739 I Unity   : Camera2: focal length3.8
12-28 10:54:00.402  4697  4739 I Unity   : Camera2: sensor size 4.5024 x 3.0912
12-28 10:54:00.402  4697  4739 I Unity   : Camera2: focal length equivalent 30
12-28 10:54:00.409  4697  4739 I Unity   : availableResolutions is not null
12-28 10:54:00.409  4697  4739 I Unity   : UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
12-28 10:54:00.409  4697  4739 I Unity   : UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
12-28 10:54:00.409  4697  4739 I Unity   : UnityEngine.Logger:Log (UnityEngine.LogType,object)
12-28 10:54:00.409  4697  4739 I Unity   : UnityEngine.Debug:Log (object)
12-28 10:54:00.409  4697  4739 I Unity   : Mediapipe.Unity.WebCamSource:get_availableResolutions () (at /Users/greg/Documents/TestMediaPipe/Assets/Samples/MediaPipe Unity Plugin/0.10.1/Official Solutions/Common/Scripts/ImageSource/WebCamSource.cs:122)
12-28 10:54:00.409  4697  4739 I Unity   : Mediapipe.Unity.WebCamSource:GetDefaultResolution () (at /Users/greg/Documents/TestMediaPipe/Assets/Samples/MediaPipe Unity Plugin/0.10.1/Official Solutions/Common/Scripts/ImageSource/WebCamSource.cs:257)
12-28 10:54:00.409  4697  4739 I Unity   : Mediapipe.Unity.WebCamSource:set_webCamDevice (System.Nullable`1<UnityEngine.WebCamDevice>) (at /Users/greg/Documents/TestMediaPipe/Assets/Samples/MediaPipe Unity Plugin/0.10.1/Official Solutions/Common/Scripts/ImageSource/WebCamSource.cs:84)
12-28 10:54:00.409  4697  4739 I Unity   : Mediapipe.Unity.WebC
</sub>

**Comment by homuler** [comment] 2022-12-28 10:20
Will you share the complete log?
The above log does not contain the error message.

> The camera works in other apps.

Do you mean you can call `WebCamDevice#availableSolutions` in other apps?

**Comment by homuler** [comment] 2022-12-28 10:36
> I have send you end of the log and it ends this way exactly. So it looks like there is some system error and it doesn't even terminate properly but just quits.

Did the sample app crash?

**Comment by gb2111** [comment] 2022-12-28 11:03
Yes. The app is quietly terminated. There will be no more logs since app is not running any more.

**Comment by homuler** [comment] 2022-12-28 11:46
I feel that we aren't reproducing the issue correctly, since at first `NullReferenceException: Object reference not set to an instance of an object` [was thrown](https://github.com/homuler/MediaPipeUnityPlugin/issues/821#issuecomment-1366009819).

What I am thinking is:
1. Unity has a bug and `WebCamDevice#availableResolutions` can be null on Samsung S22 Ultra (not verified)
2. We can avoid this error by falling back to `_defaultAvailableResolutions` when `avaiableResolutions == null`
   - If just accessing it  cause the app to crash, we can't do that, but it contradicts the fact that `NullReferenceException` was thrown at first.

In addition to that, I am wondering if you are not getting the logs correctly (e.g. the buffer size is too small, filter is not appropriate, etc...). What is the exact command you ran to get the log? (note that `adb logcat | grep -e "Unity"` won't output the crash log)

If the app was terminated, usually Android runtime will report it, so I wonder `adb logcat Unity:V native:V tflite:V CRASH:E AndroidRuntime:E "*:S"` should output something.
At any rate, since the exception was originally raised, I think it is less likely that the log of the cause cannot be retrieved.

So I'd like you to:
- check if `WebCamDevice#availableResultions` can be accessed on your phone (write a simple app to do so) to examine if 1. is the case.
- try to get the log and if possible, identify the exact code that is causing the crash.

**Comment by gb2111** [comment] 2022-12-30 16:05
Hello. I have only basic skills in unity so it must wait a bit longer for me to check `WebCamDevice#availableResultions`.
I tried logcat using command that you have provided and each time output was like I show you last time.
I checked also apk from https://google.github.io/mediapipe/solutions/pose.html and it doesn't work at all. I am 95% sure this is something wrong with my phone,

Regards

**Comment by gb2111** [comment] 2023-01-17 13:30
@homuler 
I hope you are well. I tried recently after resetting the system on my phone. Now it seems I have camera issue but pose is not being detected. On my other phones all works well. I am attaching full logs that I got with your command line.
I wonder if there is anything we can add to capture problem.
[logs.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10435457/logs.txt)

**Comment by homuler** [comment] 2023-01-17 13:43
Will you download `MediaPipeUnityPlugin-all.zip` from [the release page](https://github.com/homuler/MediaPipeUnityPlugin/releases) and build the sample app (without importing the plugin into another project)?

**Comment by homuler** [comment] 2023-01-17 13:49
It's possible that the inference steps take a long time, so I recommend that you change the camera resolution and set a larger value to `timeoutMillisec` (cf. https://github.com/homuler/MediaPipeUnityPlugin/issues/661#issuecomment-1189705966).
You can do both at runtime from the sample app UI.

P.S. Are you using Vulkan as the rendering API? If so, try OpenGL ES.

**Comment by gb2111** [comment] 2023-01-19 14:00
Hello. I tried two compilation. Async and Non Blockng Sync.
Not sure how I can change rendering api. I tried increase timeout but there was no difference.

With Async camera is working continously without pose detection and after about 30 seconds starts playing like one frame between 1 or 2 seconds and some articacts appear. Logs below.
[logs_async.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10457373/logs_async.txt)

With Non Blocking Sync is same as Async but camera problems with glitches start after 5 or 10 seconds. Logs below.
[logs_nonblockingsync.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10457374/logs_nonblockingsync.txt)

I'd guess that there is something wrong not with the camera but some deadlock in mediapipe processing.

Greg

**Comment by homuler** [comment] 2023-01-19 14:39
- What is your camera resolution? (try 1280x720 or below)
   ![camera-resolution](https://user-images.githubusercontent.com/4690128/213470894-59a6ab2e-af9d-4e71-abcb-32c0e7e9857a.png)
- Try the sync mode (not the non-blocking sync mode)
- Change the model complexity to `Lite`
- Turn off segmentation
   ![pose-config](https://user-images.githubusercontent.com/4690128/213470872-0ca55ce7-4bed-4497-8478-d858037071dd.png)
- Output the result (e.g. `Debug.Log(poseDetection)`) and check if MediaPipe is running correctly.
   https://github.com/homuler/MediaPipeUnityPlugin/blob/f5d2361f4c7442cfbf174901a165104f7298b587/Assets/MediaPipeUnity/Samples/Scenes/Pose%20Tracking/PoseTrackingSolution.cs#L98

**Comment by gb2111** [comment] 2023-01-20 11:35
Here is log from sync plus added log you suggested. You see how rarely if pose detection logged. Also when it is logged I can see new frame from camera with some detections from time to time.
[logs_sync.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10465856/logs_sync.txt)


What do you think?

**Comment by homuler** [comment] 2023-01-20 11:49
- Please *do everything* what I wrote (e.g. you didn't disable segmentation).
- Please share the video.
   - Please also open the `Pose Tracking Configuration` and `Image Source Settings` window in the video.
- Please log landmarks, too (`Debug.Log(poseLandmarks)`)

> What do you think?

I suspect that you are running the app with very heavy settings.

**Comment by gb2111** [comment] 2023-01-20 13:48
Hello. I have done all steps you require.
Here is logs file
[long_sync2.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10466787/long_sync2.txt)

Landmarks are logged as well. The log start with `poseDetection = `

Video - I am using Windows Phone Link so you see a mouse but it is real phone
https://user-images.githubusercontent.com/22025896/213711355-28169764-193a-4fd6-8e4f-55120733e24e.mp4

I tried below apk and it sometimes takes a while to initialize but eventually it works
https://google.github.io/mediapipe/solutions/pose.html#main-example

Let me know if need anything else.

**Comment by homuler** [comment] 2023-01-20 15:07
I'm sorry, there are several causes I can think of, but without the actual device in hand, I can't say anything more.

Only what I can say is that it takes about 16 seconds to process each frame.
Is it possible that Windows Phone Link is causing the slow down?

> I tried below apk and it sometimes takes a while to initialize but eventually it works

Does the official sample run much faster?

P.S. If you're logging `poseLandmarks` (`Debug.Log(poseLandmarks)`), then it's OK, but note that `poseDetection` is different from `poseLandmarks`.
> Landmarks are logged as well. The log start with poseDetection =

**Comment by gb2111** [comment] 2023-01-20 16:30
Yes. The official example works. Sometime it start fast, sometimes it takes a while to initliaze.
I think I was logging poseDetection which you asked 2 posts before poseLandmarks. Will that help is I send poseLandmarks?

**Comment by gb2111** [comment] 2023-01-20 17:59
I tried on Samsung Galaxy s10e and this time app crashes and we can see something. The original mediapipe demo works.
[logs_galaxy-s10e.txt](https://github.com/homuler/MediaPipeUnityPlugin/files/10468884/logs_galaxy-s10e.txt)

**Comment by homuler** [comment] 2023-01-22 14:03
> I tried below apk and it sometimes takes a while to initialize but eventually it works

Please built an apk using [mediapipe v0.8.10](https://github.com/google/mediapipe/tree/v0.8.10), on which the plugin depends, and see if it works or not.

If it doesn't work, then this is caused by the MediaPipe itself.
Otherwise, there is nothing more I can do here with the given information.

> I tried on Samsung Galaxy s10e and this time app crashes

Maybe it's the same issue as #730 .

**Comment by gb2111** [comment] 2023-01-22 16:16
Okey. So I have compiled native demo on mediapipe v0.8.10 and it has same issue like when using plugin. I have frame every 5-10 seconds and sometimes small artifacts. As I said before, precompiled native demo that have probably a year or more works. Also I have compiled native app with most recent code and it works.

Regards

**Comment by homuler** [comment] 2023-01-29 08:25
@gb2111 Will you check to see if https://github.com/homuler/MediaPipeUnityPlugin/commit/fbc8b125d5249b4dd389c7d24d39cd6c8595b954 fixes your issue?
You can download the built package from https://github.com/homuler/MediaPipeUnityPlugin/actions/runs/4035174241

**Comment by gb2111** [comment] 2023-01-30 12:04
It works!!!!!
Sometimes it doesn't work right after installation and need close app and start it again. But other then that it works on Samsuns S22 Ultra and Samsung Galaxy s10e. Thank you so much!!!

**Comment by homuler** [comment] 2023-01-30 13:43
Thanks.

> Sometimes it doesn't work right after installation and need close app and start it again.

I'm not sure but it may be related to an existing issue (e.g. #828). 
Please open a new issue if necessary. Now I close this issue.

**Closed by homuler** 2023-01-30 13:43 UTC
Labels: platform:android, type:support
