### ISSUE TITLE
PoseTrackingGraph::Stop() tries to call methods on null objects 

### ISSUE THREAD

**Issue by wonwoolee** [homuler/MediaPipeUnityPlugin#546] opened 2022-05-03 08:01 UTC
### Plugin Version or Commit ID

v0.9.1

### Unity Version

2020.3.32f1

### Your Host OS

Ubuntu 20.04

### Target Platform

Android

### Build Command

python build.py build --desktop gpu --android arm64 --opencv cmake 

### Bug Description

When PoseTrackingGraph runs in Async mode, output stream object are not initialized and remain as null. 
However `PoseTrackingGraph Stop()` method always tries to call `RemoveAllListeners()` method on them, and thus NullReferenceException is raised. 

```
public override void Stop()
{
      _poseDetectionStream.RemoveAllListeners();
      _poseDetectionStream = null;
      _poseLandmarksStream.RemoveAllListeners();
      _poseLandmarksStream = null;
      _poseWorldLandmarksStream.RemoveAllListeners();
      _poseWorldLandmarksStream = null;
      _segmentationMaskStream.RemoveAllListeners();
      _segmentationMaskStream = null;
      _roiFromLandmarksStream.RemoveAllListeners();
      _roiFromLandmarksStream = null;
      base.Stop();
 }
```

### Steps to Reproduce the Bug

Please see Bug Description.

### Log

NullReferenceException: Object reference not set to an instance of an object
Mediapipe.Unity.PoseTracking.PoseTrackingGraph.Stop () (at Assets/Scripts/PoseTrackingGraph.cs:117)
Mediapipe.Unity.GraphRunner.OnDestroy () (at Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs:104)

**Comment by homuler** [comment] 2022-05-06 05:24
Will you describe how to reproduce the error?

> Please see Bug Description.

You have written about the causes you consider, but it is not correct (`OutputStream` objects will be initialized in async mode).
I have a feeling there is an execution path where this error occurs, but if it's not frequent, I'd like to leave it for a while.

**Comment by MoneyWonders** [comment] 2022-05-09 06:35
It seems because the Stop() was called twice.
The parameter will be null in the first time, and NullReferenceException in the second time.
You can add "?" to avoid it.
_poseDetectionStream?.RemoveAllListeners();

**Comment by homuler** [comment] 2022-05-09 09:00
@MoneyWonders If you know how to reproduce the error, please let me know.

**Comment by MoneyWonders** [comment] 2022-05-10 01:42
This issue happens because GraphRunner will call Stop() in it's OnDestroy(), and ImageSourceSolution do the same thing in Stop().
If you like to stop MediaPipe before close app, you will meet this issue.
I think the better way to avoid this problem is add null-check in GraphRunner.Stop(), just like:
public override void Stop()
{
    _palmDetectionsStream?.RemoveAllListeners();
    _palmDetectionsStream = null;
    _handRectsFromPalmDetectionsStream?.RemoveAllListeners();
    _handRectsFromPalmDetectionsStream = null;
    _handLandmarksStream?.RemoveAllListeners();
    _handLandmarksStream = null;
    _handWorldLandmarksStream?.RemoveAllListeners();
    _handWorldLandmarksStream = null;
    _handRectsFromLandmarksStream?.RemoveAllListeners();
    _handRectsFromLandmarksStream = null;
    _handednessStream?.RemoveAllListeners();
    _handednessStream = null;
    base.Stop();
}

**Comment by wonwoolee** [comment] 2022-05-12 01:32
I agree with the solution @MoneyWonders proposed, which is simple and elegant 😄
I applied it to my code and it addressed my issue.

**Closed** 2022-05-12 08:26 UTC
Labels: type:bug, sect:sample app
