### ISSUE TITLE
Inference time decreasing after a certain delay using GPUBuffer packets

### ISSUE THREAD

**Issue by ABazL** [homuler/MediaPipeUnityPlugin#1140] opened 2024-01-30 11:25 UTC
### Plugin Version or Commit ID

0.10.3

### Unity Version

2021.3.9f1

### Your Host OS

Windows 10

### Target Platform

Android

### Description

Hello,

I'm experiencing a weird behaviour by using GPUBuffer packets for pose tracking.
After a certain delay (could be several seconds or even one to two minutes), inference time decrease and depending the smartphone I use, it can decrease a lot.
For example on a Xiaomi Redmi Note 10 Pro I can have an inference time of 45/50ms and after some dozen of seconds, inference take about 12ms (On Samsung S20Fe 5G, inference time is about 35/37ms and decrease to 27/28ms after some delay).

I've tried to profile GPU usage through Unity Profiler in order to check if there was some delay for the GPU to really start working effeciently after some delay.

On Xiaomi Redmi Note 10 Pro, I can see some traffic on GPU usage during the phase where inference time is high and when inference time decrease I see that GPU usage is quite stabilize.
On Samsung S20 Fe 5G, everything seems stabilize but I can clearly see the gap on GPU usage between when inference is about 35ms and when it's about 27ms.

Redmi Note 10 Pro:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/7339fc98-c57e-4a0f-9af1-9f90aa809606)

S20 Fe 5G:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/13f7474e-2471-4940-bb3a-32b6601a3d28)

I thought it could be due to pose detection phase but it seems very long for this phase only.

Not sure how I could interpret this behaviour but I've some theory in mind: 
- either GPU needs to deal with some data first and put them in GPU cache before well processing inference
- or MediaPipe is processing first on CPU and then processing on GPU when GPU is fully ready
- or there is some parameter to pass when launching the app on Android for using full power of GPU and CPU (I already check battery saver options and they are not enabled).

Maybe you'll have some ideas about this behaviour ?

Thanks!

**Comment by homuler** [comment] 2024-01-30 14:40
Can you reproduce this behaviour with the latest [Pose Landmark Detection scene](https://github.com/homuler/MediaPipeUnityPlugin/blob/b6961e5590274898755cd1212508b7e4f3459e45/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Pose%20Landmark%20Detection/Pose%20Landmark%20Detection.unity)?

**Comment by ABazL** [comment] 2024-01-30 17:08
Thanks for your quick answer!

> Can you reproduce this behaviour with the latest [Pose Landmark Detection scene](https://github.com/homuler/MediaPipeUnityPlugin/blob/b6961e5590274898755cd1212508b7e4f3459e45/Assets/MediaPipeUnity/Samples/Scenes/Tasks/Pose%20Landmark%20Detection/Pose%20Landmark%20Detection.unity)?

I tried and I didn't reproduce the issue but inference rate seems clearly less important than the prototype project I use so not sure I can really compare (I explain a bit below the context of my prototype project).
Not sure also where I could add a Stopwatch in this example using GLContext, could you point out where GPUBuffer packet is sent to the input stream and which callback will be triggered ?

For a bit more context of how I send packet through your API, I'm not using FlowLimiter node and I send GPUBuffer packet as soon as previous frame as been processed by MediaPipe (as soon as the callback has been triggered) without waiting the end of the current frame => I'm not using coroutine nor MainThread to send Packet to MediaPipe, I'm running a Task that launch a async function who's in charge of waiting for camera to deliver a fresh new image (different from previous one) and waiting for last frame to be processed by MediaPipe, then prepare and send a new Packet to MediaPipe. 

> Can you reproduce this behaviour if you disable the segmentation?

![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/d9143680-0ec6-4a9d-8ae4-8942b15d2489)
By setting "enable_segmentation" to false I still have this delay before having improvement in inference time.
Just to be sure, if not explicitly set to true, isn't it disabled by default ?
Above is the result I have on GPU usage on Redmi Note 10 Pro, difference is less important between where inference time is important (45/50ms) and where inference time is clearly improved (~12ms), it corresponds to the red line approximatively.

Thanks a lot!

**Comment by homuler** [comment] 2024-01-31 13:50
> I tried and I didn't reproduce the issue but inference rate seems clearly less important than the prototype project I use so not sure I can really compare

I'm sorry, could you clarify what you mean by "less important"?

> For a bit more context of how I send packet through your API

If it's not that you can reproduce the issue with the sample scene of this project, then I can't answer the question since I can't investigate the issue.
Furthermore, if you want to know how MediaPipe works internally, please ask the MediaPipe developer.

**Comment by ABazL** [comment] 2024-01-31 14:02
By "less important" I meant that the inference rate I had with the sample project you shared seem lower than the one I can have on the prototype onwhich I'm working on.

I've done some profiling with Snapdragon Profiler on Redmi Note 10 Pro and it seems that the issue come from when the GPU allocate "full" clock speed to the app process:
![image](https://github.com/homuler/MediaPipeUnityPlugin/assets/135328094/69d26d9e-7fe9-4aac-9773-9bc0bec4ee68)

I'll try to check how from a Unity project I could say that the app need as many GPU resources as possible from the beginning of the app or from a specific point at runtime.
If I don't find more informations about this, I'll start a discussion with MediaPipe developers indeed.
Would you like me to share a link to the discussion here if I start one about this topic maybe ?

Thanks for your help!

**Comment by homuler** [comment] 2024-01-31 14:37
> Would you like me to share a link to the discussion here if I start one about this topic maybe ?

In the scope of what I wanted to know, I've understood the cause, so you don't need to let me know, thanks.

**Comment by homuler** [comment] 2024-02-03 16:28
I thing the GPU is operating only at boost clock, so I will close this issue.

**Closed by homuler** 2024-02-03 16:28 UTC
Labels: type:support
