### ISSUE TITLE
WebCam stuck in prevoius Scene after loading a new scene

### ISSUE THREAD

**Issue by AliSaeidiRad** [homuler/MediaPipeUnityPlugin#245] opened 2021-08-14 13:43 UTC
hi everyone,
i am building a game with mediapipe unity plugin that you can control your player with your hand but when character reaches to the end of the game i load next level with SceneManager my webcam still running on previous scene.
i tried Application.LoadLevel but it still stuck in prevoius scene
i used OnDisable() function in SceneDirector.cs and it has no effect on webcam
i dont know what else should i do
so can anyone help me?

thanks.

**Comment by jsaon-L** [comment] 2021-08-18 05:27
you need add function to close camera

**Comment by jsaon-L** [comment] 2021-08-18 05:32
![image](https://user-images.githubusercontent.com/17309378/129842613-26587c7e-7554-46c4-9dc2-871130f6ded1.png)
![image](https://user-images.githubusercontent.com/17309378/129842651-3c306fe9-0c23-4f76-8aa4-bd601847131f.png)

**Comment by AliSaeidiRad** [comment] 2021-08-18 05:57
you totally saved me 😄 
Thanks a lot 😄

**Comment by jsaon-L** [comment] 2021-08-18 06:20
I'm glad I can help you

**Comment by jsaon-L** [comment] 2021-08-19 08:41
I don't know the cause of the problem
my approach is to just turn off the camera
and dontDestroy SceneDirector gameobject

**Comment by homuler** [comment] 2021-09-26 07:21
Fixed by #296

**Closed by homuler** 2021-09-26 07:21 UTC
